library(taxonomizr)
getNamesAndNodes()
getAccession2taxid()
getAccession2taxid(types='prot')
read.names.sql('names.dmp','accessionTaxa.sql', overwrite = TRUE)
read.nodes.sql('nodes.dmp','accessionTaxa.sql',overwrite = TRUE)
read.accession2taxid(list.files('.','accession2taxid.gz$'),'accessionTaxa.sql')
blastResults<-read.table("blastx_output.out",header=FALSE,stringsAsFactors=FALSE)
accessions<-sapply(strsplit(blastResults[,2],'\\|'),'[',2)
taxaId<-accessionToTaxa(accessions,"accessionTaxa.sql")
taxonomy<-getTaxonomy(taxaId,'accessionTaxa.sql')
write.csv(taxonomy,"blastx_taxonomy.csv")